spring.datasource.url=jdbc:postgresql://localhost:5432/pasajeya
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.base-url=http://localhost:8080
app.frontend.url=http://localhost:4200

# -- reCAPTCHA v2 (test keys de Google, siempre pasan en localhost) --
app.recaptcha.secret=6LdBahMtAAAAAMlBoaZeLFuTb14dG7sacuWJceO_
app.recaptcha.site-key=6LdBahMtAAAAAAVzHU70oZj6JRe0Pq8Scd228RM5
app.recaptcha.enabled=true
